# Generated by Django 5.2.10 on 2026-02-20 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_habit_completed_habit_user_habitlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habit',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='habitlog',
            old_name='completed_date',
            new_name='date',
        ),
        migrations.AlterUniqueTogether(
            name='habitlog',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='habit',
            name='description',
        ),
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='plant_type',
            field=models.CharField(choices=[('rose', 'Rose'), ('cactus', 'Cactus'), ('sunflower', 'Sunflower')], default='rose', max_length=50),
        ),
        migrations.AddField(
            model_name='habitlog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.habit'),
        ),
    ]
