# Generated by Django 5.2.10 on 2026-02-21 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_habit_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='name',
        ),
        migrations.RemoveField(
            model_name='habit',
            name='plant_type',
        ),
        migrations.AddField(
            model_name='habit',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='habit',
            name='title',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='habit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.habit'),
        ),
    ]
