# Generated by Django 5.2.10 on 2026-02-23 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_habit_frequency_remove_habit_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='plant_stage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='habit',
            name='streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habit',
            name='total_completions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='habitlog',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
