# Generated by Django 5.2.10 on 2026-02-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_habit_plant_stage_habit_streak_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='frequency',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
